version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bookservice-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookservice
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: bookservice-redis
    ports:
      - "6388:6379"
    command: [ "redis-server", "--port", "6379" ]

  bookservice:
    build: .
    container_name: bookservice-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bookservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6388

volumes:
  mysql-data:
